# Generated by Django 2.1.4 on 2019-02-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='Player ID')),
                ('salt', models.CharField(max_length=5, verbose_name="Player's salt")),
                ('physical_game_point', models.IntegerField(default=0, verbose_name='Physical Game Point')),
                ('ctr_tournament_point', models.IntegerField(default=0, verbose_name='CTR (Tournament) Point')),
                ('ctr_free_play_point', models.IntegerField(default=0, verbose_name='CTR (Free Play) Point')),
                ('cerdas_cermat_point', models.IntegerField(default=0, verbose_name='Cerdas Cermat Point')),
                ('ranking_1_point', models.IntegerField(default=0, verbose_name='Ranking 1 Point')),
                ('guitar_hero_point', models.IntegerField(default=0, verbose_name='Guitar Hero Point')),
                ('cs_go_point', models.IntegerField(default=0, verbose_name='CS:GO Point')),
                ('winning_eleven_point', models.IntegerField(default=0, verbose_name='Winning Eleven Point')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
    ]
