# Generated by Django 2.1.4 on 2019-02-10 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Player ID'),
        ),
    ]
