# Generated by Django 2.1.4 on 2019-02-11 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0003_auto_20190211_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='first_name',
            field=models.CharField(default='', max_length=32, verbose_name='First Name'),
        ),
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(default='', max_length=32, verbose_name='Last Name'),
        ),
        migrations.AddField(
            model_name='player',
            name='username',
            field=models.CharField(default='', max_length=32, verbose_name='Username'),
        ),
    ]
