# Generated by Django 2.1.4 on 2019-02-12 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple', '0008_auto_20190212_0530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='physical_game_point',
        ),
        migrations.AddField(
            model_name='player',
            name='baby_rattle_point',
            field=models.IntegerField(default=0, verbose_name='Baby Rattle Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='floating_ball_race_point',
            field=models.IntegerField(default=0, verbose_name='Floating Ball Race Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='human_table_soccer_point',
            field=models.IntegerField(default=0, verbose_name='Huma Table Soccer Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='inferno_extinguisher_point',
            field=models.IntegerField(default=0, verbose_name='Inferno Extinguisher Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='jumping_the_riddles_point',
            field=models.IntegerField(default=0, verbose_name='Jumping the Riddles Point'),
        ),
        migrations.AddField(
            model_name='player',
            name='move_up_cup_point',
            field=models.IntegerField(default=0, verbose_name='Move Up Cup Point'),
        ),
    ]
